version: '3.7'

services:
    app:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./selfcheckout:/app
        environment:
            - EMAIL=<email@gmail.com>
            - PASSWORD=<password>
            - HOST=smtp.gmail.com   # no need to change this if using gmail.com
            - API_SERVER=https://api-ap.hosted.exlibrisgroup.com  
            - API=<your_api>
            - CIRC_DESK=<circ_desk>
            - LIBRARY=<library>
            - DEBUG=1
        command: >
            sh -c  "python manage.py runserver 0.0.0.0:8000"